### ISSUE TITLE
测试在电脑上没问题，但手机上白屏

### ISSUE THREAD

**Issue by mangobuge** [StanleySong/flarum-ext-auth-wechat#4]
有遇到同样情况的吗？
处于白屏状态的链接是如下情况：
http://www.xxxxx.xxxxx/auth/wechat?code=011fKlLV05nn1V1sPNIV0WokLV0fKlLX&state=6W8bbMS9AqImarxyUu3IPitE26ARYAN5

**Comment by sxhuan** [comment]
Yes this is an issue,  I will try to fix it when i have time

**Comment by maxpy** [comment]
同白屏，给个解决思路也行， 从哪些文件下手？

**Comment by maxpy** [comment]
@StanleySong 是不是都放弃 flarum 了啊？

**Comment by sxhuan** [comment]
sorry  I was too busy to work on it, I am in travel now , when I get back , I can take a look.

**Comment by maxpy** [comment]
I found the bug
wechat js no `window.opener` 
In 'AuthenticationResponseFactory.php' file getResponse function 
I change the payload to  
` $content ='<script> window.location.href="/";</script>'; `

`        if (stripos($_SERVER['HTTP_USER_AGENT'],'mobile')=== false){ `
        `  $content = sprintf(`
           `   '<script>window.opener.app.authenticationComplete(%s); window.close();</script>',`
           `   json_encode($payload)`
      `    );
        }`

**Comment by sxhuan** [comment]
@maxpy thanks. i will update it
